name: 'Triangle CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.3.5

#    - name: Build 32bit Traingle utility
#      run: ./siskin triangle.nest %triangle-x86
#    - name: Build 32bit Tricall test app
#      run: ./siskin triangle.nest %tricall-x86
#    - name: Test 32bit Triangle
#      run:  ./build/triangle-x86
#    - name: Test 32bit Tricall
#      run:  ./build/tricall-x86

    - name: Build 64bit Traingle utility
      run: ./siskin triangle.nest %triangle-x64
    - name: Build 64bit Tricall test app
      run: ./siskin triangle.nest %tricall-x64
    - name: Test 64bit Triangle
      run:  ./build/triangle-x64
    - name: Test 64bit Tricall
      run:  ./build/tricall-x64

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: Triangle-windows-CI-${{github.run_id}}
        path: ./build/*

   linux:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.3.5

    - name: Build 64bit Traingle utility
      run: ./siskin triangle.nest %triangle-x64
    - name: Build 64bit Tricall test app
      run: ./siskin triangle.nest %tricall-x64
    - name: Test 64bit Triangle
      run:  ./build/triangle-x64
    - name: Test 64bit Tricall
      run:  ./build/tricall-x64

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: Triangle-linux-CI-${{github.run_id}}
        path: ./build/*

   macos:
    strategy:
      fail-fast: true
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.3.5

    - name: Build 64bit Traingle utility
      run: ./siskin triangle.nest %triangle-x64
    - name: Build 64bit Tricall test app
      run: ./siskin triangle.nest %tricall-x64
    - name: Test 64bit Triangle
      run:  ./build/triangle-x64
    - name: Test 64bit Tricall
      run:  ./build/tricall-x64

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: Triangle-osx-CI-${{github.run_id}}
        path: ./build/*